### PR TITLE
Trigger recovery if a socket write fails

### LINKED ISSUE #341: When server closes TCP connection because TCP window is full, connection recovery does not kick in
## Summary

We started seeing the following in production:

```
java.net.SocketException: Broken pipe
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
	at java.io.DataOutputStream.flush(DataOutputStream.java:123)
	at com.rabbitmq.client.impl.SocketFrameHandler.flush(SocketFrameHandler.java:177)
	at com.rabbitmq.client.impl.AMQConnection.flush(AMQConnection.java:559)
	at com.rabbitmq.client.impl.AMQCommand.transmit(AMQCommand.java:127)
	at com.rabbitmq.client.impl.AMQChannel.quiescingTransmit(AMQChannel.java:396)
	at com.rabbitmq.client.impl.AMQChannel.transmit(AMQChannel.java:372)
	at com.rabbitmq.client.impl.AMQChannel.transmit(AMQChannel.java:365)
	at com.rabbitmq.client.impl.ChannelN.basicAck(ChannelN.java:1169)
	at com.rabbitmq.client.impl.recovery.RecoveryAwareChannelN.basicAck(RecoveryAwareChannelN.java:89)
	at com.rabbitmq.client.impl.recovery.AutorecoveringChannel.basicAck(AutorecoveringChannel.java:436)
	at RMQProblemTest$1.handleDelivery(RMQProblemTest.java:87)
	at com.rabbitmq.client.impl.ConsumerDispatcher$5.run(ConsumerDispatcher.java:149)
	at com.rabbitmq.client.impl.ConsumerWorkService$WorkPoolRunnable.run(ConsumerWorkService.java:100)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

After looking at a packet capture, we were seeing `[TCP Window Full]` messages when RabbitMQ was sending to our consumer followed by a ton of `[TCP ZeroWindow]` frames coming from the consumer. After enough of these, RabbitMQ abruptly closes the connection by sending a `RST` frame and reporting only this in the logs:

```
=ERROR REPORT==== 10-Jan-2018::20:38:08 ===
closing AMQP connection <0.5373.1> ([::1]:53814 -> [::1]:5672):
{writer,send_failed,{error,timeout}}
```

Further investigation revealed that I was setting the QoS for the consumer only *AFTER* I had already started consuming (i.e. I was calling `basicConsume` directly before `basicQos`). I realize that this was wrong of me, however, it seems odd that this would cause the exception above especially with such a relatively small number of small messages. The more concerning thing is that none of the recovery/shutdown methods on either the connection or channel seemed to be called despite the fact that the connection was indeed closed.

## Reproduction

I made a little test project that shows the issue.

https://github.com/vincentjames501/rmq-fail/blob/master/src/test/java/RMQProblemTest.java

Running the test will show the issue after 30 seconds or so. It appears reproducible on most RabbitMQ versions but I documented by setup below.

## Environment

RabbitMQ server - *3.6.12*
Erlang - *Erlang 20.1*
Operating system version (and distribution, if applicable) - *OSX 10.13.2*
All client libraries used - *RabbitMQ Java Client 4.4.1*
RabbitMQ plugins (if applicable) - *Just Management Console*

### Thanks!

### PR DESCRIPTION
**Pull request by acogoluegnes**
Detecting connection failure on reading can take a lot of time
(even forever if the reading thread is stuck), so connection
recovery can now be triggered when a write operation fails.
This can make the client more reactive to detect failing connections.

Closes #341.

### CODE REVIEW

**Comment by michaelklishin** [comment]
I like where this is headed. The test is likely going to be pretty fragile in some environments, though.

**Comment by acogoluegnes** [comment]
This PR changes the initial test a bit: it publishes a message in the listener instead of ack-ing the delivery. This can trigger a write error as expected. When using manual ack, the recovery could hang as the broker was busy re-enqueueing messages. This would make connection recovery freeze when re-registering the consumer. This is more of a broker issue, hence the initial test change.

Here's a capture of the top plugin when the broker hangs on message re-enqueueing:

screenshot from 2018-02-09 17 26 32

**Comment by michaelklishin** [comment]
With this version I observe a successful recovery [using this reproduction test](https://github.com/vincentjames501/rmq-fail/blob/master/src/test/java/RMQProblemTest.java) provided in #341:

```
2018-02-14 17:20:11.863 [info] <0.1005.0> accepting AMQP connection <0.1005.0> ([::1]:64548 -> [::1]:5672)
2018-02-14 17:20:12.085 [info] <0.1005.0> Connection <0.1005.0> ([::1]:64548 -> [::1]:5672) has a client-provided name: Producer Connection
2018-02-14 17:20:12.096 [info] <0.1005.0> connection <0.1005.0> ([::1]:64548 -> [::1]:5672 - Producer Connection): user 'guest' authenticated and granted access to vhost '/'
2018-02-14 17:20:12.112 [info] <0.1018.0> accepting AMQP connection <0.1018.0> ([::1]:64549 -> [::1]:5672)
2018-02-14 17:20:12.114 [info] <0.1018.0> Connection <0.1018.0> ([::1]:64549 -> [::1]:5672) has a client-provided name: Consuming Connection
2018-02-14 17:20:12.116 [info] <0.1018.0> connection <0.1018.0> ([::1]:64549 -> [::1]:5672 - Consuming Connection): user 'guest' authenticated and granted access to vhost '/'
2018-02-14 17:20:13.927 [info] <0.1005.0> closing AMQP connection <0.1005.0> ([::1]:64548 -> [::1]:5672 - Producer Connection, vhost: '/', user: 'guest')
2018-02-14 17:20:43.553 [warning] <0.1018.0> closing AMQP connection <0.1018.0> ([::1]:64549 -> [::1]:5672 - Consuming Connection):
{writer,send_failed,{error,timeout}}
2018-02-14 17:21:11.298 [info] <0.1067.0> accepting AMQP connection <0.1067.0> ([::1]:64563 -> [::1]:5672)
2018-02-14 17:21:11.303 [info] <0.1067.0> Connection <0.1067.0> ([::1]:64563 -> [::1]:5672) has a client-provided name: Consuming Connection
2018-02-14 17:21:11.305 [info] <0.1067.0> connection <0.1067.0> ([::1]:64563 -> [::1]:5672 - Consuming Connection): user 'guest' authenticated and granted access to vhost '/'
```

```
Consumed so far - 18
Consumed so far - 19
Recovery Started for Consuming Connection amqp://guest@0:0:0:0:0:0:0:1:5672/
Recovery Started for Consuming Channel AMQChannel(amqp://guest@0:0:0:0:0:0:0:1:5672/,1)
Recovery finished for Consuming Channel AMQChannel(amqp://guest@0:0:0:0:0:0:0:1:5672/,1)
Recovery finished for Consuming Connection amqp://guest@0:0:0:0:0:0:0:1:5672/
Consumed so far - 19
Consumed so far - 19
Consumed so far - 20
Consumed so far - 20
```

**Comment by vincentjames501** [comment]
Great work everyone!

**Comment by michaelklishin** [comment]
@acogoluegnes should we release a 4.5.0 RC1 or just a milestone for now?

**Comment by acogoluegnes** [comment]
@michaelklishin 4.5.0 is feature-complete, so we can release 4.5.0.RC1.

File: src/main/java/com/rabbitmq/client/impl/AMQConnection.java [hunk 1]
```diff
@@ -245,10 +252,17 @@ public AMQConnection(ConnectionParams params, FrameHandler frameHandler, Metrics
         this._inConnectionNegotiation = true; // we start out waiting for the first protocol response
 
         this.metricsCollector = metricsCollector;
+
+        this.errorOnWriteListener = params.getErrorOnWriteListener() != null ? params.getErrorOnWriteListener() :
+            new ErrorOnWriteListener() {
+                @Override
+                public void handle(Connection connection, IOException exception) { }
```
Comment (vikinghawk) [inline src/main/java/com/rabbitmq/client/impl/AMQConnection.java]: to maintain passivity shouldn't this rethrow the exception instead of swallow it?

Comment (michaelklishin) [reply src/main/java/com/rabbitmq/client/impl/AMQConnection.java]: Can you clarify what you mean by "passivity" here? The goal of this listener is to kick off connection recovery first and foremost. We do not want to re-throw anything in that case as there won't be anything to catch it.

Comment (acogoluegnes) [reply src/main/java/com/rabbitmq/client/impl/AMQConnection.java]: Yes, this should re-throw the exception as-is in this case (hence passivity). This applies only to non-recoverable connections. The [listener is called in the `flush` method](https://github.com/rabbitmq/rabbitmq-java-client/blob/e934ed31156731965bcb68c90e2382db5d64876d/src/main/java/com/rabbitmq/client/impl/AMQConnection.java#L569-L575) and at first the exception was always re-thrown after the call to the listener. I then switched the exception handling in the listener to give it more control but forgot to reflect it in this default, no-op implementation. Again, this impacts only non-recoverable connections (when the user disables automatic connection recovery explicitly), `AutorecoveringConnection` [sets up a listener that triggers connection recovery](https://github.com/rabbitmq/rabbitmq-java-client/blob/e934ed31156731965bcb68c90e2382db5d64876d/src/main/java/com/rabbitmq/client/impl/recovery/AutorecoveringConnection.java#L103-L126). Thanks for pointing this out @vikinghawk!
