### PR TITLE
Log UnknownChannelException in connection loop

### LINKED ISSUE #189: UnknownChannelException in AMQConnection.MainLoop.run
Encountered this error in my ExceptionHandler.handleUnexpectedConnectionDriverException method a couple times on version 3.6.3 with connection and topology recovery enabled.

Message: RabbitExceptionHandler: Caught unexpected connection driver exception for connection XXX
Throwable: com.rabbitmq.client.impl.UnknownChannelException: Unknown channel number 147
	at com.rabbitmq.client.impl.ChannelManager.getChannel(ChannelManager.java:82)
	at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:560)

Looks to me like there is possibility MainLoop is processing a frame with a channel number that doesn't exist in ChannelManager? Not sure how that is possible and I can't reliably reproduce... Could potentially handle this scenario in a better way though?

### PR DESCRIPTION
**Pull request by acogoluegnes**
Fixes #189

### CODE REVIEW

File: src/main/java/com/rabbitmq/client/impl/AMQConnection.java [hunk 1]
```diff
@@ -554,7 +559,17 @@ public void run() {
...
                                     if (cm != null) {
-                                        cm.getChannel(frame.channel).handleFrame(frame);
+                                        ChannelN channel;
+                                        try {
+                                            channel = cm.getChannel(frame.channel);
+                                        } catch(UnknownChannelException e) {
+                                            // this can happen if channel has been closed,
+                                            // but there was e.g. an in-flight delivery.
+                                            // just ignoring the frame to avoid closing the whole connection
+                                            LOGGER.info("Channel {} is unknown, ignoring frame", frame.channel);
```
Comment (michaelklishin) [inline src/main/java/com/rabbitmq/client/impl/AMQConnection.java]: I'd change the wording to "Received a frame on an unknown channel, ignoring it"

File: src/main/java/com/rabbitmq/client/impl/AMQConnection.java [hunk 2]
```diff
@@ -554,7 +559,17 @@ public void run() {
...
                                     if (cm != null) {
-                                        cm.getChannel(frame.channel).handleFrame(frame);
+                                        ChannelN channel;
+                                        try {
+                                            channel = cm.getChannel(frame.channel);
+                                        } catch(UnknownChannelException e) {
+                                            // this can happen if channel has been closed,
+                                            // but there was e.g. an in-flight delivery.
+                                            // just ignoring the frame to avoid closing the whole connection
+                                            LOGGER.info("Received a frame on an unknown channel, ignoring it");
```
Comment (michaelklishin) [inline src/main/java/com/rabbitmq/client/impl/AMQConnection.java]: Sorry, I didn't mean that you should use this message exactly. I think logging channel ID of the frame is still a good idea :)

**Comment by michaelklishin** [comment]
Will update the copy myself.
